### ISSUE TITLE
Investigating the Ubuntu 18.04 test logs generated by xCAT Jenkins test environment

### ISSUE THREAD

**Issue by neo954** [xcat2/xcat2-task-management#214] opened 2018-06-22 06:48 UTC
Open bugs for xCAT if needed.

* [x] Investigating test logs against Ubuntu 18.04 on x86-64
* [x] Investigating test logs against Ubuntu 18.04 on ppc64el

**Comment by hu-weihua** [comment] 2018-07-09 04:48
Due to xcat ubuntu18.04 support can not finished in 2.14.2 sprint2, this task will last to 2.14.3 sprint 1.  Move it to 2.14.3 sprint 1.

**Comment by hu-weihua** [comment] 2018-07-19 09:20
3 daily regression projects have been added into automation production environment and logged all defects. So close this task.

**Closed** 2018-07-19 09:20 UTC
Labels: sprint1
